### ISSUE TITLE
 Cannot request a page callback without first specifying the page.

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/remote_datasource#31]
User Notice: GenericErrorHandler 1024: Cannot request a page callback without first specifying the page. on line 317 of file /Users/user1/Sites/www.site1.com/symphony/lib/core/class.administration.php

<dsrss url="http://www.biztechafrica.com/feed/rss/country/angola/">
        <error>Cannot request a page callback without first specifying the page.</error>
 </dsrss>

**Comment by nitriques** [comment]
Could you try to give me the complete stack ?

**Comment by nitriques** [comment]
Closed as we do not have any feedback.

**Comment by wdebusschere** [comment]
Nitriques, i'm using the Remote Datasource Integration branch and when I add an XML, i alwas get in the debug mode: Cannot request a page callback without first specifying the page.

**Comment by nitriques** [comment]
Do you have weird looking errors in Symphony's log ?

**Comment by nitriques** [comment]
It's really weird because the only place where that Exception is thrown is in the `getPageCallback` core method, which is not called at all in this extension.

Can you give me the url of the remote xml file so I can test ?

**Comment by nitriques** [comment]
Does it works if you turn off caching ? (cache = 0)

**Comment by wdebusschere** [comment]
Remote Datasource 2.2.1
Cache was 0

Any XML gives an error even very basic ones..

Symphony log:
06/18/2016 8:10 pm > User Notice: GenericErrorHandler 1024: Cannot request a page callback without first specifying the page. on line 318 of file /Users/xxx/xxx/xxx/symphony/lib/core/class.administration.php
<img width="588" alt="screen shot 2016-06-18 at 19 14 46" src="https://cloud.githubusercontent.com/assets/4136426/16172849/f237e298-3588-11e6-8194-77036515a576.png">

**Comment by wdebusschere** [comment]
Nitriques,
Had this error on all my symphony installations, error is because of the Static Section extension, which throws the error.. There might be a conflict somewhere.. Disabling the Static Section extension solved it. =)

**Comment by nitriques** [comment]
Static section is deprecated! Use https://github.com/DeuxHuitHuit/limit_section_entries instead!
