### ISSUE TITLE
Search in cached data?

### ISSUE THREAD

**Issue by animaux** [symphonycms/remote_datasource#32]
Is there any way to access the cached data for a fulltext search? I guess there’s no straightforward way to use `search index` with external date?

**Comment by nitriques** [comment]
I am not sure I totally understand. You want to index something from a remote DS ? You'd better go without this... Or create you're search in xslt... But AFAIK, this extension does not handle well xml responses larger than a Mb...

**Comment by animaux** [comment]
> You want to index something from a remote DS ?
Yup, was wondering if it would have been possible. However we are already switching to a timed XML-import instead. Hope the cron-stuff is still working well in 2.6.x

> AFAIK, this extension does not handle well xml responses larger than a Mb...
Oops. Good to know. Maybe we should ad a hint about this in the readme? Import will definitely be the better approach.

Thanks!

**Comment by nitriques** [comment]
my pleasure.
