### ISSUE TITLE
Symphony Fatal Database Error: Column 'start_number' cannot be null

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/remote_datasource#40]
Not entering a start number gives an error:
Symphony Fatal Database Error: Column 'start_number' cannot be null

Solution:
- Making start number a required field
- Default value 1 for start number

**Comment by nitriques** [comment]
Are you sure you are reporting this against the right extension ?
Do you have a stack trace ?

**Comment by wdebusschere** [comment]
I had an older version. New version doesn't have this problem anymore.
