### ISSUE TITLE
External URLs return 400 error

### ISSUE THREAD

**Issue by pixelninja** [symphonycms/remote_datasource#41]
This is probably user error, but when I try save a remote datasource with an external URL for an xml file, it returns a 400 error. 

`Failed to load URL, status code 400 was returned. `

If i edit the file directly and add the URL, I get this error within the debug output

`<error>Status code 400 was returned. Content-type: text/html; charset=iso-8859-1</error>`

The XML passes validation, and I have the XML format selected. 

Is there something I'm missing? I thought it might be permissions, but playing with those didn't work. I tried using the URL that the site is on, and also uploading the file to another site I manage and trying that. Same result either way.

Noting that it works locally, pointing to a local URL. It's just the live instance.

Cheers!

**Comment by nitriques** [comment]
Note that it is 99.99999% sure that problem is not in the code (but rather a configuration issue). You can roll out the firewall thing, because you would not get a 400, you would get connection refused or timeout.

**Comment by pixelninja** [comment]
Hi @nitriques, thanks for the reply.

Here is the URL, http://206.189.66.88/freedom_uploads/funeral-template.xml. It passes validation. Note the IP until it's a live site. Is there a namespace perhaps that needs passing? Not that It's using any...

Screenshot of DS settings: https://ibb.co/caxxj9

**Comment by wdebusschere** [comment]
@pixelninja I just tried this with your xml link and i get the data correctly in the ?debug.
symphony 2.7.7 and remote datasource 2.3.0.

Maybe try to put this code in a test php script and run on your server

```
<?php
function download_page($path){
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL,$path);
    curl_setopt($ch, CURLOPT_FAILONERROR,1);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION,1);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER,1);
    curl_setopt($ch, CURLOPT_TIMEOUT, 15);
    $retValue = curl_exec($ch);          
    curl_close($ch);
    return $retValue;
}

$sXML = download_page('http://206.189.66.88/freedom_uploads/funeral-template.xml');

var_dump($sXML);die;
```

**Comment by pixelninja** [comment]
bah! I knew it would be user error. 

I have a new server set up, and the php-curl module isn't installed by default. Silly.

I installed it (for those in the same boat `sudo apt-get install php7.0-curl`), restarted apache and voila.

Thanks for your help @nitriques and @wdebusschere.
